### ISSUE TITLE
Any Binaries Available for us non-programing mortals??

### ISSUE THREAD

**Issue by momashi** [elitak/PPJoy#3]
Hi, I was so happy when I stumbled upon this github project. I've been looking for a 64bit compatible version of PPJoy but the original dev's links are dead. There's plenty of copies of PPJoy out there but they're all heavily laced with  Spyware, Trojans and viruses (getting 23 out 46 hits on Virus Total). I've downloaded the source but I'm having alot of trouble compiling it (I have no experience with compiling in Windows). Can anyone post a compiled version of this little piece of loveliness with a SHA1 signature? Maybe even open a googlesource page to make it obvious for those looking for it out there. If it would help, I would even volunteer to open the googlesource project page myself, give ownership status to Eric Litak and the current devs in the github and try to get the original Dev to post a link to the googlesource/github pages on his official PPJoy blogspot.

**Comment by Quench0** [comment]
@elitak 
Hi, this is 3 years late, but I've downloaded the original source from the base of your Master branch and have managed to fix it so it will compile with the original build tools. Including fixing the CPL source file. Since Internet searches for the source land here it seems logical that you host it (as another branch maybe). Are you interested?

Thanks.

**Comment by thenebular** [comment]
I don't know about @elitak, but I sure would love it.

**Comment by Quench0** [comment]
@thenebular 
No worries, if @elitak doesn't respond over the next few days, then I'll upload the changes somewhere.

**Comment by elitak** [comment]
Yes, I can merge any changes you have made. Either submit a pull request through github or send me a tarball. I suggest the former, but you can email me the tarball if need be; same account name at gmail.

**Comment by momashi** [comment]
Hi,  do  you  think I could have  copy of that source code. Never succeeded compiling the old one but maybe I'll have better luck with yours. I'm guessing this one will work with test signing.

**Comment by Quench0** [comment]
Well, I decided to use this opportunity to learn the basics of GitHub and published the source myself with build instructions: https://github.com/Quench0/PPJoy
In total, 6 files are modified. It essentially uses the original MS build tools to build the original source.
@elitak please feel free to publish none/some/all from my fork. As I originally mentioned since internet searches come here, it would be nice if you host a working build.

The tragedy is that I had a code-signing certificate that expired literally a week before I came across the need for these drivers :-(

**Comment by elitak** [comment]
Usually it's best to fork the repository rather than recreate it, that way you get to use github's pull request feature and other tools, especially if we're sharing the same starting point in the abandoned code.

I've integrated each of your commits, but flattened the directory structure. Since I'm probably never going to work on this anymore, I could transfer ownership of this repository to you so that github redirects all the search results landing on my URI to yours. To do that: Clone my repo and verify that it's identical to yours and builds properly. Then, delete yours off of github (keep a local copy of course), message me again, and I will transfer ownership of this one to you.

**Comment by Quench0** [comment]
Thanks for that. I wasn't sure about forking your branch because you had done work on it to compile with a later version of Visual Studio and I didn't want to try undoing it. So I did my own repo starting with Deons original source.
BTW, I also posted a binary - essentially the only difference to what's out there is that I've added Windows Control Panel Joystick applet to the PPJoy Start menu/Programs to easily test the joystick.

I've updated the README.md just thanking Deon for his work. Since we both have the same repository name I don't think I can fork yours to do a pull request. So up to you if you want to update that file.

You may as well keep ownership of your repository so people will still find it. I have no further plans to do anymore work on it unless if sometime in the future I get access to a code-signing certificate to fully sign the drivers.

Thanks, and take care.

**Comment by elitak** [comment]
They do have the same name. That's why you would have to delete yours from github so that when I transfer mine to you it takes its place. When a repository moves on github, a redirection is left behind in the old place leading visitors to the new. If you're not planning on doing any further work, then I guess it isn't necessary.

Even if you don't want ownership I recommend you delete yours and then fork mine, that way we have the same revision history so people are not given the impression our repositories are any different from each other.

Again, right now, the latest commit in my repo should mirror the contents in yours, except for the flattened directory structure.

**Comment by Quench0** [comment]
Thanks, I've deleted my repository and forked yours. Have also made a pull request for the README.md to thank Deon for his work.

I've also added a built binary as a release to my fork so feel free if you want to include it.

Cheers.

**Comment by elitak** [comment]
I've mirrored your binary release. Closing now.
